# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: bionic
latex: false # we're going to use tinytex
cache:
  packages: true
  directories:
    - $HOME/.fonts    # Where fonts are downloaded to & installed
    - $HOME/.TinyTex  
    - $TRAVIS_BUILD_DIR/_bookdown_files   # Rendered images cache

apt_packages:
  - fonts-oflb-asana-math # Asana Math font for, well, math
  - fonts-roboto          # Roboto font family for a slightly more modern look
  - libv8-dev
  - libgit2-dev
  - libxml2-dev
  # - fonts-roboto-slab     # Serif-Roboto
  # - fonts-firacode        # my go-to monospace font
  
# Set github dependencies
r_github_packages: 
  - dkahle/dirichlet
  - michael-franke/aida-package

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook", quiet = TRUE)'
  # - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book", quiet = TRUE)'
  
# after_success:
#   - |
#     sed -i 's/pre{overflow:auto;word-wrap:normal;margin:0 0 1.275em;padding:.85em 1em;/pre{overflow:auto;word-wrap:normal;margin:0 0 0;padding:0 1em;/g' $TRAVIS_BUILD_DIR/_book/libs/gitbook-2.6.7/css/style.css


deploy:
  provider: pages
  skip_cleanup: true
  token: $INTRO_DA
  keep_history: true
  on:
    branch: master
  local_dir: _book
  target_branch: gh-pages
